ln -sf ~/dotfiles/.vimrc ~/.vimrc
ln -sf ~/dotfiles/.zshrc ~/.zshrc
ln -sf ~/dotfiles/.tmux.conf ~/.tmux.conf
ln -sf ~/dotfiles/tmux-window.sh ~/tmux-window.sh
ln -sf ~/dotfiles/dircolors.256dark ~/dircolors.256dark
ln -sf ~/dotfiles/.tmux-powerlinerc ~/.tmux-powerlinerc
ln -sf ~/dotfiles/.gitconfig  ~/.gitconfig
ln -sf ~/dotfiles/.gitignore_global ~/.gitignore_global
ln -sf ~/dotfiles/antigen.zsh ~/antigen.zsh
ln -sf ~/dotfiles/my_smt.zsh-theme ~/.oh-my-zsh/custom/themes/my_smt.zsh-theme
ln -sf ~/dotfiles/mytheme.sh ~/tmux-powerline/themes/mytheme.sh
ln -sf ~/dotfiles/i3.config ~/.config/i3/config
